### ISSUE TITLE
NullPointerException when try to getOrCreateContext

### ISSUE THREAD

**Issue by vasgat** [helios-h2020/h.core-SocialEgoNetwork#4]
The following exception appears when try to create a new context after I have performed a removeContext action in the ego netowork.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at eu.h2020.helios_social.core.contextualegonetwork.Context.load(Context.java:100)
        at eu.h2020.helios_social.core.contextualegonetwork.Context.assertLoaded(Context.java:112)
        at eu.h2020.helios_social.core.contextualegonetwork.Context.getData(Context.java:135)
        at eu.h2020.helios_social.core.contextualegonetwork.ContextualEgoNetwork.getOrCreateContext(ContextualEgoNetwork.java:205)

**Comment by maniospas** [comment]
Replicated bug as multiple runs of the test eu.h2020.helios_social.core.contextualegonetwork.examples.ExampleRemoveContext.
Fixed bug by adding previously omitted operations when removing context and updated javadoc.
